
pin-threads=[4,5]
blas-threads=1
rest-api-port=8001
input-channel="aeron:ipc"
input-stream=1013

output-channel="aeron:ipc"
output-stream=2001

[state]
reference-image="/mnt/datadrive/DATA/LOWFS/reference-image.fits"
dark="/mnt/datadrive/DATA/LOWFS/dark.fits"
image-mask="/mnt/datadrive/DATA/LOWFS/image-mask.fits"
cog-image-mask="/mnt/datadrive/DATA/LOWFS/cog-image-mask.fits"
slopes-to-TT="/mnt/datadrive/DATA/LOWFS/slopes-to-TT.fits"
cog-reference="/mnt/datadrive/DATA/LOWFS/cog-reference.fits"
image-to-modes="/mnt/datadrive/DATA/LOWFS/image-to-modes.fits"
modes-to-actus="/mnt/datadrive/DATA/LOWFS/modes-to-actus.fits"